# Generated by Django 5.1.5 on 2025-02-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='city_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='WeatherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField()),
                ('temp', models.FloatField()),
                ('desc', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.citymodel')),
            ],
        ),
    ]
