# Generated by Django 5.1.5 on 2025-02-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_weathermodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermodel',
            name='temp',
            field=models.CharField(),
        ),
    ]
