# Generated by Django 5.1.5 on 2025-02-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_alter_weathermodel_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathermodel',
            name='sun_rise',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='weathermodel',
            name='sun_set',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='weathermodel',
            name='temp',
            field=models.FloatField(),
        ),
    ]
