# Generated by Django 5.1.5 on 2025-02-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_weathermodel_sun_rise_weathermodel_sun_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermodel',
            name='sun_rise',
            field=models.CharField(default='No Data'),
        ),
        migrations.AlterField(
            model_name='weathermodel',
            name='sun_set',
            field=models.CharField(default='No Data'),
        ),
    ]
