# Generated by Django 5.1.5 on 2025-02-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_alter_weathermodel_sun_rise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermodel',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weathermodel',
            name='sun_rise',
            field=models.CharField(default='No Data', max_length=50),
        ),
        migrations.AlterField(
            model_name='weathermodel',
            name='sun_set',
            field=models.CharField(default='No Data', max_length=50),
        ),
    ]
