# Generated by Django 5.1.5 on 2025-02-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_alter_weathermodel_date_alter_weathermodel_sun_rise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathermodel',
            name='sun_rise',
        ),
        migrations.RemoveField(
            model_name='weathermodel',
            name='sun_set',
        ),
    ]
